---
- name: creating playbook for checksum
  hosts: all
  become: true
  vars_files:
    - files_list.yml
  tasks:
    - name: getting current checksum
      stat:
        path: "{{item.name}}"
      with_items: "{{ files}}"
      register: test

    - debug:
        msg: 'checksum is matched'
      when: '"{{item.item.checksum}}" == "{{item.stat.checksum}}"'
      with_items: "{{test.result}}"

    - debug:
        msg: 'checksum not matched'
      when: '"{{item.item.checksum}}" =! "{{item.stat.checksum}}"'
      with_items: "{(test.result}}"
