---
- hosts: all
  become: true
  vars_files:
    - files_list.yml
  tasks:
    - name: checking checksup
      stat:
        path: "{{ item.name }}"
      with_items: "{{files}}"
      register: test

    - debug:
        msg : "checksum matched"
      when: '"{{ item.item.checksum }}" == "{{ item.stat.checksum }}"'
      with_items: "(( test.result }}"

    - debug:
        msg: "checksum not matched"
      when: '"{{item.item.checksum}}" =! "{{item.stat.checksum}}"'
      with_items: "{{ test.results }}"
